version: '3'

services:
  moodle:
    build: ./docker/moodle
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./siteroot:/siteroot
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Mysecretpassw0rd
    volumes:
      - 'db:/var/lib/postgresql'
  test-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Mysecretpassw0rd
    volumes:
      - 'testdb:/var/lib/postgresql'
volumes:
    db:
    testdb: